CREATE TABLE `album` (
    `id` INT unsigned NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `image` (
    `id` INT unsigned NOT NULL AUTO_INCREMENT,
    `album_id` INT unsigned NOT NULL,
    PRIMARY KEY (`id`),
    FOREIGN KEY (`album_id`) REFERENCES `album` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO album VALUES (1),(2),(3),(4),(5);

INSERT INTO image VALUES (NULL,1),(NULL,1),(NULL,1),(NULL,1),(NULL,1);
INSERT INTO image VALUES (NULL,2),(NULL,2),(NULL,2),(NULL,2),(NULL,2),(NULL,2),(NULL,2),(NULL,2),(NULL,2),(NULL,2),(NULL,2),(NULL,2),(NULL,2),(NULL,2),(NULL,2),(NULL,2),(NULL,2),(NULL,2),(NULL,2),(NULL,2);
INSERT INTO image VALUES (NULL,3),(NULL,3),(NULL,3),(NULL,3),(NULL,3),(NULL,3),(NULL,3),(NULL,3),(NULL,3),(NULL,3),(NULL,3),(NULL,3),(NULL,3),(NULL,3),(NULL,3),(NULL,3),(NULL,3),(NULL,3),(NULL,3),(NULL,3),(NULL,3),(NULL,3),(NULL,3),(NULL,3);
INSERT INTO image VALUES (NULL,4),(NULL,4),(NULL,4),(NULL,4),(NULL,4),(NULL,4),(NULL,4),(NULL,4),(NULL,4),(NULL,4),(NULL,4),(NULL,4),(NULL,4),(NULL,4),(NULL,4),(NULL,4),(NULL,4),(NULL,4),(NULL,4),(NULL,4),(NULL,4),(NULL,4),(NULL,4),(NULL,4),(NULL,4),(NULL,4);
INSERT INTO image VALUES (NULL,5),(NULL,5),(NULL,5),(NULL,5),(NULL,5),(NULL,5),(NULL,5),(NULL,5),(NULL,5),(NULL,5),(NULL,5),(NULL,5),(NULL,5),(NULL,5),(NULL,5),(NULL,5),(NULL,5),(NULL,5),(NULL,5),(NULL,5),(NULL,5),(NULL,5),(NULL,5),(NULL,5),(NULL,5),(NULL,5),(NULL,5),(NULL,5),(NULL,5),(NULL,5),(NULL,5),(NULL,5),(NULL,5),(NULL,5);